In [1]:
import pandas as pd

df0 = pd.read_csv( 'Raw Data_Paylater and Non Paylater User.csv' , sep = ';' )

df0.describe()

,Gender,E-Paylater User Status,Educational Background,Year of Birth,Job Status,Monthly Income,Average monthly expenditure for online shopping in relation to monthly income,IBB1,IBB2,IBB3,...,SC1,SC2,SC3,SC4,SC5,NE1,NE2,NE3,NE4,NE5
count,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,...,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000
mean,1.680247,1.251852,2.285185,1994.111111,1.640741,2.808642,1.506173,3.053086,2.749383,2.803704,...,3.774074,3.851852,2.814815,2.883951,3.135802,3.525926,3.516049,3.574074,3.379012,3.122222
std,0.466669,0.434345,1.162412,10.020745,0.777031,1.849511,0.800548,1.116633,1.166129,1.098256,...,0.804542,0.846882,0.977005,0.997581,1.125643,1.163918,1.075799,1.121790,1.105466,1.161230
min,1.000000,1.000000,1.000000,1966.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,1.000000,1987.000000,1.000000,1.000000,1.000000,2.000000,2.000000,2.000000,...,3.000000,4.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000,2.000000
50%,2.000000,1.000000,3.000000,1999.000000,2.000000,2.000000,1.000000,3.000000,3.000000,3.000000,...,4.000000,4.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,3.000000,3.000000
75%,2.000000,2.000000,3.000000,2002.000000,2.000000,4.000000,2.000000,4.000000,4.000000,4.000000,...,4.000000,4.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
max,2.000000,2.000000,4.000000,2005.000000,4.000000,6.000000,6.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

 Let's extract the relevant columns:

In [2]:
df = df0[  ['IBB1', 'IBB2', 'IBB3', 'Gender', 'E-Paylater User Status', 'Monthly Income',
            'IBB4', 'P1', 'P2', 'P3', 'P4',
            'SI1', 'SI2', 'SI3', 'SI4', 'SI5', 'SI6',
            'H1', 'H2', 'H3', 'H4',
            'SC1', 'SC2', 'SC3 ', 'SC4 ', 'SC5',
            'NE1', 'NE2', 'NE3', 'NE4', 'NE5']  ]

df.describe()

,IBB1,IBB2,IBB3,Gender,E-Paylater User Status,Monthly Income,IBB4,P1,P2,P3,...,SC1,SC2,SC3,SC4,SC5,NE1,NE2,NE3,NE4,NE5
count,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.00000,...,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000
mean,3.053086,2.749383,2.803704,1.680247,1.251852,2.808642,2.418519,2.307407,2.395062,2.24321,...,3.774074,3.851852,2.814815,2.883951,3.135802,3.525926,3.516049,3.574074,3.379012,3.122222
std,1.116633,1.166129,1.098256,0.466669,0.434345,1.849511,1.191815,1.220172,1.215668,1.16133,...,0.804542,0.846882,0.977005,0.997581,1.125643,1.163918,1.075799,1.121790,1.105466,1.161230
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,...,3.000000,4.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000,2.000000
50%,3.000000,3.000000,3.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.00000,...,4.000000,4.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,3.000000,3.000000
75%,4.000000,4.000000,4.000000,2.000000,2.000000,4.000000,3.000000,3.000000,4.000000,3.00000,...,4.000000,4.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
max,5.000000,5.000000,5.000000,2.000000,2.000000,6.000000,5.000000,5.000000,5.000000,5.00000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

 Next let's use the `rename` function to give the columns simpler variable names:

In [3]:
df = df.rename( columns={'E-Paylater User Status':'Status', 'Monthly Income': 'Income', 'SC3 ': 'SC3', 'SC4 ':'SC4'} )   # column SC3 and SC4 have redundant spaceback in the dataset

df.describe()

,IBB1,IBB2,IBB3,Gender,Status,Income,IBB4,P1,P2,P3,...,SC1,SC2,SC3,SC4,SC5,NE1,NE2,NE3,NE4,NE5
count,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.00000,...,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000
mean,3.053086,2.749383,2.803704,1.680247,1.251852,2.808642,2.418519,2.307407,2.395062,2.24321,...,3.774074,3.851852,2.814815,2.883951,3.135802,3.525926,3.516049,3.574074,3.379012,3.122222
std,1.116633,1.166129,1.098256,0.466669,0.434345,1.849511,1.191815,1.220172,1.215668,1.16133,...,0.804542,0.846882,0.977005,0.997581,1.125643,1.163918,1.075799,1.121790,1.105466,1.161230
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,...,3.000000,4.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000,2.000000
50%,3.000000,3.000000,3.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.00000,...,4.000000,4.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,3.000000,3.000000
75%,4.000000,4.000000,4.000000,2.000000,2.000000,4.000000,3.000000,3.000000,4.000000,3.00000,...,4.000000,4.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
max,5.000000,5.000000,5.000000,2.000000,2.000000,6.000000,5.000000,5.000000,5.000000,5.00000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [4]:
replacement_value = {1: 0, 2: 1}

df['Status'] = df['Status'].replace(replacement_value)
df['Gender'] = df['Gender'].replace(replacement_value)

df.describe()

,IBB1,IBB2,IBB3,Gender,Status,Income,IBB4,P1,P2,P3,...,SC1,SC2,SC3,SC4,SC5,NE1,NE2,NE3,NE4,NE5
count,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.00000,...,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000
mean,3.053086,2.749383,2.803704,0.680247,0.251852,2.808642,2.418519,2.307407,2.395062,2.24321,...,3.774074,3.851852,2.814815,2.883951,3.135802,3.525926,3.516049,3.574074,3.379012,3.122222
std,1.116633,1.166129,1.098256,0.466669,0.434345,1.849511,1.191815,1.220172,1.215668,1.16133,...,0.804542,0.846882,0.977005,0.997581,1.125643,1.163918,1.075799,1.121790,1.105466,1.161230
min,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.000000,2.000000,2.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.00000,...,3.000000,4.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000,2.000000
50%,3.000000,3.000000,3.000000,1.000000,0.000000,2.000000,2.000000,2.000000,2.000000,2.00000,...,4.000000,4.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,3.000000,3.000000
75%,4.000000,4.000000,4.000000,1.000000,1.000000,4.000000,3.000000,3.000000,4.000000,3.00000,...,4.000000,4.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
max,5.000000,5.000000,5.000000,1.000000,1.000000,6.000000,5.000000,5.000000,5.000000,5.00000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

 One common phenomenon in surveying is straightlining where respondents select the same answer to the question due to various reasons (Juita et al., 2024, pg 6), which counts their responses as outliers. We will search for this phenomenon inside the dataset and remove it if detected.

In [5]:
def straightline_detection(file):
    num_col = 34     # number of questions
    straightline_drop = []

    for n in range(len(file)):
        row = file.iloc[n]      # read each row inside the file
        most_common_answer = row.value_counts()      # return the row number and frequencies of the outputs inside
        most_common_answer_counts = row.value_counts().max()     #  return the row number and the output with the highest frequency
        if most_common_answer_counts > 0.7 * num_col:      # the number reponse that accounts more than 70% of the questions
            straightline_drop.append(n)

    file = file.drop(straightline_drop, axis = 0)
    return file    

df = straightline_detection(df)

In [6]:
# calculate the mean for each variables
df['P'] = df[['P1', 'P2', 'P3', 'P4']].mean(axis = 1)
df['SC'] = df[['SC3', 'SC4', 'SC5']].mean(axis = 1)
df['SI'] = df[['SI1', 'SI2', 'SI3', 'SI4', 'SI5', 'SI6']].mean(axis = 1)
df['NE'] = df[['NE1', 'NE2', 'NE3', 'NE4', 'NE5']].mean(axis = 1)
df['H'] = df[['H1', 'H2', 'H3', 'H4']].mean(axis = 1)
df['IBB'] = df[['IBB1', 'IBB2', 'IBB3', 'IBB4']].mean(axis = 1)

In [7]:
# dropping previous indicators

df = df.drop(['P1', 'P2', 'P3', 'P4', 'SC1', 'SC2', 'SC3', 'SC4', 'SC5', 'SI1', 'SI2', 'SI3', 'SI4', 'SI5', 'SI6', 'NE1', 'NE2', 'NE3', 'NE4', 'NE5',
              'H1', 'H2', 'H3', 'H4', 'IBB1', 'IBB2', 'IBB3', 'IBB4'], axis = 1)

In [8]:
df.describe()

,Gender,Status,Income,P,SC,SI,NE,H,IBB
count,803.000000,803.000000,803.000000,803.000000,803.000000,803.000000,803.000000,803.000000,803.000000
mean,0.682441,0.251557,2.806974,2.326588,2.946866,2.349315,3.424159,3.498132,2.751868
std,0.465817,0.434178,1.847382,1.116592,0.860738,0.990528,0.890439,0.832905,0.878709
min,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,1.000000,1.000000,2.333333,1.500000,2.800000,3.000000,2.000000
50%,1.000000,0.000000,2.000000,2.000000,3.000000,2.166667,3.400000,3.750000,2.750000
75%,1.000000,1.000000,4.000000,3.250000,3.666667,3.000000,4.000000,4.000000,3.500000
max,1.000000,1.000000,6.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000