# parse_data.ipynb

This notebook parses the data files used for the FP-2 assignment. 

<br>
<br>

First let's read the attached data file:

In [3]:
import pandas as pd

df0 = pd.read_csv( 'Raw Data_Paylater and Non Paylater User.csv' , sep = ';' )

df0.describe()

,Gender,E-Paylater User Status,Educational Background,Year of Birth,Job Status,Monthly Income,Average monthly expenditure for online shopping in relation to monthly income,IBB1,IBB2,IBB3,...,SC1,SC2,SC3,SC4,SC5,NE1,NE2,NE3,NE4,NE5
count,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,...,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000
mean,1.680247,1.251852,2.285185,1994.111111,1.640741,2.808642,1.506173,3.053086,2.749383,2.803704,...,3.774074,3.851852,2.814815,2.883951,3.135802,3.525926,3.516049,3.574074,3.379012,3.122222
std,0.466669,0.434345,1.162412,10.020745,0.777031,1.849511,0.800548,1.116633,1.166129,1.098256,...,0.804542,0.846882,0.977005,0.997581,1.125643,1.163918,1.075799,1.121790,1.105466,1.161230
min,1.000000,1.000000,1.000000,1966.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,1.000000,1987.000000,1.000000,1.000000,1.000000,2.000000,2.000000,2.000000,...,3.000000,4.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000,2.000000
50%,2.000000,1.000000,3.000000,1999.000000,2.000000,2.000000,1.000000,3.000000,3.000000,3.000000,...,4.000000,4.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,3.000000,3.000000
75%,2.000000,2.000000,3.000000,2002.000000,2.000000,4.000000,2.000000,4.000000,4.000000,4.000000,...,4.000000,4.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
max,2.000000,2.000000,4.000000,2005.000000,4.000000,6.000000,6.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

<br>
<br>

The dependent, independent, and control variables (DVs, IVs, and CVs) that we are interested in are:

**DVs**:
- IBB1: Respondents do most of their online shopping spontaneously
- IBB2: Respondents make purchases without planning, and they do not intend to shop when opening the application
- IBB3: Respondents have no desire to shop before opening the application
- IBB4: Respondents cannot resist shopping on the application

**IVs**:
- Promotion (column 'P1' -> 'P4' inside the csv file)
- Social Influence (column 'SI1' -> 'SI6' inside the csv file)
- Happiness (column 'H1' -> 'H4' inside the csv file)
- Self-Control (column 'SC1' -> 'SC5' inside the csv file)
- Normative Evaluation (column 'NE1' -> 'NE5' inside the csv file)

**CVs**:
- Gender: Male or Female
- E-Paylater User Status: Whether respondents have used or have never used E-Paylater services
- Monthly Income: Divided into 6 levels

<br>
<br>

Let's extract the relevant columns:

In [5]:
df = df0[  ['IBB1', 'IBB2', 'IBB3', 'Gender', 'E-Paylater User Status', 'Monthly Income',
            'IBB4', 'P1', 'P2', 'P3', 'P4',
            'SI1', 'SI2', 'SI3', 'SI4', 'SI5', 'SI6',
            'H1', 'H2', 'H3', 'H4',
            'SC1', 'SC2', 'SC3 ', 'SC4 ', 'SC5',
            'NE1', 'NE2', 'NE3', 'NE4', 'NE5']  ]

df.describe()

,IBB1,IBB2,IBB3,Gender,E-Paylater User Status,Monthly Income,IBB4,P1,P2,P3,...,SC1,SC2,SC3,SC4,SC5,NE1,NE2,NE3,NE4,NE5
count,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.00000,...,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000
mean,3.053086,2.749383,2.803704,1.680247,1.251852,2.808642,2.418519,2.307407,2.395062,2.24321,...,3.774074,3.851852,2.814815,2.883951,3.135802,3.525926,3.516049,3.574074,3.379012,3.122222
std,1.116633,1.166129,1.098256,0.466669,0.434345,1.849511,1.191815,1.220172,1.215668,1.16133,...,0.804542,0.846882,0.977005,0.997581,1.125643,1.163918,1.075799,1.121790,1.105466,1.161230
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,...,3.000000,4.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000,2.000000
50%,3.000000,3.000000,3.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.00000,...,4.000000,4.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,3.000000,3.000000
75%,4.000000,4.000000,4.000000,2.000000,2.000000,4.000000,3.000000,3.000000,4.000000,3.00000,...,4.000000,4.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
max,5.000000,5.000000,5.000000,2.000000,2.000000,6.000000,5.000000,5.000000,5.000000,5.00000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

<br>
<br>

Next let's use the `rename` function to give the columns simpler variable names:

In [7]:
df = df.rename( columns={'E-Paylater User Status':'Status', 'Monthly Income':'Income', 'SC3 ': 'SC3', 'SC4 ':'SC4'} )   # column SC3 and SC4 have redundant spaceback in the dataset

df.describe()

,IBB1,IBB2,IBB3,Gender,Status,Income,IBB4,P1,P2,P3,...,SC1,SC2,SC3,SC4,SC5,NE1,NE2,NE3,NE4,NE5
count,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.00000,...,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000,810.000000
mean,3.053086,2.749383,2.803704,1.680247,1.251852,2.808642,2.418519,2.307407,2.395062,2.24321,...,3.774074,3.851852,2.814815,2.883951,3.135802,3.525926,3.516049,3.574074,3.379012,3.122222
std,1.116633,1.166129,1.098256,0.466669,0.434345,1.849511,1.191815,1.220172,1.215668,1.16133,...,0.804542,0.846882,0.977005,0.997581,1.125643,1.163918,1.075799,1.121790,1.105466,1.161230
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,...,3.000000,4.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000,2.000000
50%,3.000000,3.000000,3.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.00000,...,4.000000,4.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,3.000000,3.000000
75%,4.000000,4.000000,4.000000,2.000000,2.000000,4.000000,3.000000,3.000000,4.000000,3.00000,...,4.000000,4.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
max,5.000000,5.000000,5.000000,2.000000,2.000000,6.000000,5.000000,5.000000,5.000000,5.00000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000